import { allOn, fragment, off, on } from '../_contract.js';

/*
 * The `eslint` plugin: oxlint's port of the ESLint core rules, all 183
 * non-nursery ones decided by name. The offs below are the whole list, and
 * each carries the one reason that justifies it.
 */
export default fragment({
    id: 'core/eslint',
    plugins: ['eslint'],
    rules: {
        ...allOn([
            'accessor-pairs',
            'array-callback-return',
            'block-scoped-var',
            'class-methods-use-this',
            'constructor-super',
            'curly',
            'default-case',
            'default-case-last',
            'default-param-last',
            'eqeqeq',
            'for-direction',
            'func-name-matching',
            'func-names',
            'getter-return',
            'grouped-accessor-pairs',
            'guard-for-in',
            'id-denylist',
            'id-match',
            'logical-assignment-operators',
            'max-classes-per-file',
            'max-nested-callbacks',
            'new-cap',
            'no-alert',
            'no-array-constructor',
            'no-async-promise-executor',
            'no-await-in-loop',
            'no-bitwise',
            'no-caller',
            'no-case-declarations',
            'no-class-assign',
            'no-compare-neg-zero',
            'no-cond-assign',
            'no-console',
            'no-const-assign',
            'no-constant-binary-expression',
            'no-constant-condition',
            'no-constructor-return',
            'no-control-regex',
            'no-debugger',
            'no-delete-var',
            'no-div-regex',
            'no-dupe-class-members',
            'no-dupe-else-if',
            'no-dupe-keys',
            'no-duplicate-case',
            'no-else-return',
            'no-empty',
            'no-empty-character-class',
            'no-empty-function',
            'no-empty-pattern',
            'no-empty-static-block',
            'no-eq-null',
            'no-eval',
            'no-ex-assign',
            'no-extend-native',
            'no-extra-bind',
            'no-extra-boolean-cast',
            'no-extra-label',
            'no-fallthrough',
            'no-func-assign',
            'no-global-assign',
            'no-implicit-coercion',
            'no-implicit-globals',
            'no-import-assign',
            'no-inline-comments',
            'no-inner-declarations',
            'no-invalid-regexp',
            'no-irregular-whitespace',
            'no-iterator',
            'no-label-var',
            'no-labels',
            'no-lone-blocks',
            'no-loop-func',
            'no-loss-of-precision',
            'no-misleading-character-class',
            'no-multi-assign',
            'no-multi-str',
            'no-new',
            'no-new-func',
            'no-new-native-nonconstructor',
            'no-new-wrappers',
            'no-nonoctal-decimal-escape',
            'no-obj-calls',
            'no-object-constructor',
            'no-param-reassign',
            'no-plusplus',
            'no-promise-executor-return',
            'no-proto',
            'no-prototype-builtins',
            'no-redeclare',
            'no-regex-spaces',
            'no-restricted-globals',
            'no-restricted-imports',
            'no-restricted-properties',
            'no-return-assign',
            'no-script-url',
            'no-self-assign',
            'no-self-compare',
            'no-sequences',
            'no-setter-return',
            'no-shadow',
            'no-shadow-restricted-names',
            'no-sparse-arrays',
            'no-template-curly-in-string',
            'no-this-before-super',
            'no-unassigned-vars',
            'no-underscore-dangle',
            'no-unexpected-multiline',
            'no-unneeded-ternary',
            'no-unreachable',
            'no-unsafe-finally',
            'no-unsafe-negation',
            'no-unsafe-optional-chaining',
            'no-unused-labels',
            'no-unused-private-class-members',
            'no-unused-vars',
            'no-useless-backreference',
            'no-useless-call',
            'no-useless-catch',
            'no-useless-computed-key',
            'no-useless-concat',
            'no-useless-constructor',
            'no-useless-escape',
            'no-useless-rename',
            'no-useless-return',
            'no-var',
            'no-warning-comments',
            'no-with',
            'object-shorthand',
            'operator-assignment',
            'prefer-arrow-callback',
            'prefer-const',
            'prefer-exponentiation-operator',
            'prefer-named-capture-group',
            'prefer-numeric-literals',
            'prefer-object-has-own',
            'prefer-object-spread',
            'prefer-regex-literals',
            'prefer-rest-params',
            'prefer-spread',
            'prefer-template',
            'preserve-caught-error',
            'radix',
            'require-unicode-regexp',
            'require-yield',
            'symbol-description',
            'unicode-bom',
            'use-isnan',
            'valid-typeof',
            'vars-on-top',
            'yoda',
        ]),

        // -- On, at the strictest value the option carries --------------------
        'arrow-body-style': on(['as-needed']),
        complexity: on([12]),
        'func-style': on(['declaration', { allowArrowFunctions: true }]),
        'max-depth': on([4]),
        'max-params': on([4]),
        'no-duplicate-imports': on([{ allowSeparateTypeImports: true }]),
        'no-unmodified-loop-condition': on([{ checkConditionalExpressions: true }]),
        /* A hoisted function declaration has no temporal dead zone, and the
         * estate writes the public function first and its helpers below it.
         * The defect this rule names — reading a binding before it exists — is
         * a `let`, a `const` or a `class`, and all three stay refused. */
        'no-use-before-define': on([{ classes: true, functions: false, variables: true }]),
        'no-unused-expressions': on([
            { allowShortCircuit: true, allowTaggedTemplates: true, allowTernary: true },
        ]),
        'no-void': on([{ allowAsStatement: true }]),
        /* The object form names what it takes; the array form past index 0
         * counts commas, and `const [, , , operating] = SPINE` is not clearer
         * than `SPINE[3]`. */
        'prefer-destructuring': on([{ array: false, object: true }]),
        /* `never`, not `always`. Both exist and both fix, but the `always` fixer
         * FUSES adjacent declarations, and a comment standing between two of
         * them is pulled inside the chain — which silently relocates the
         * `// Given -` / `// Then -` narration @jterrazz/test requires. `never`
         * splits chains and leaves every comment where it stands. */
        'one-var': on(['never']),

        // -- Off, each with its one reason ------------------------------------
        'capitalized-comments': off({
            by: 'jterrazz-design — 198 of 198 reports were false positives (quality study, 2026-09-15)',
            kind: 'evidence',
        }),
        'id-length': off({
            by: 'measured on this package — every report was a conventional short binding (k, v, x)',
            kind: 'evidence',
        }),
        'init-declarations': off({ by: 'no-unassigned-vars, prefer-const', kind: 'covered' }),
        'max-lines': off({ by: 'complexity (12)', kind: 'covered' }),
        'max-lines-per-function': off({ by: 'complexity (12)', kind: 'covered' }),
        'max-statements': off({ by: 'complexity (12)', kind: 'covered' }),
        'no-continue': off({ by: 'max-depth (4)', kind: 'exclusive' }),
        'no-implied-eval': off({ by: 'typescript/no-implied-eval', kind: 'covered' }),
        'no-lonely-if': off({ by: 'unicorn/no-lonely-if', kind: 'covered' }),
        'no-magic-numbers': off({
            by: 'measured on this package — 125 reports, not one of them a defect',
            kind: 'evidence',
        }),
        'no-negated-condition': off({ by: 'unicorn/no-negated-condition', kind: 'covered' }),
        'no-nested-ternary': off({ by: 'unicorn/prefer-ternary', kind: 'exclusive' }),
        'no-ternary': off({ by: 'unicorn/prefer-ternary', kind: 'exclusive' }),
        'no-throw-literal': off({ by: 'typescript/only-throw-error', kind: 'covered' }),
        'no-undefined': off({
            by: 'no-shadow-restricted-names, no-global-assign — `undefined` cannot be rebound, which is the hazard this ES3-era rule was written for',
            kind: 'covered',
        }),
        'prefer-promise-reject-errors': off({
            by: 'typescript/prefer-promise-reject-errors',
            kind: 'covered',
        }),
        'require-await': off({ by: 'typescript/require-await', kind: 'covered' }),
        'sort-imports': off({ by: 'oxfmt sortImports', kind: 'covered' }),
        'sort-keys': off({
            by: 'docs/07-lint-presets.md — an object orders by meaning, and generic inference is order-sensitive',
            kind: 'convention',
        }),
        'sort-vars': off({ by: 'one-var (never)', kind: 'covered' }),
    },
});
