import { allOn, fragment, off, on } from '../_contract.js';

/*
 * The `unicorn` plugin, all 137 non-nursery rules decided by name. Two of the
 * offs are the formatter's: unicorn's fixer and oxfmt disagree about the same
 * bytes, and the fixpoint suite is what proves it (specs/cli/preset).
 */
export default fragment({
    id: 'core/unicorn',
    plugins: ['unicorn'],
    rules: {
        ...allOn(
            [
                'catch-error-name',
                'consistent-assert',
                'consistent-date-clone',
                'consistent-empty-array-spread',
                'consistent-existence-index-check',
                'consistent-function-scoping',
                'consistent-template-literal-escape',
                'custom-error-definition',
                'empty-brace-spaces',
                'error-message',
                'escape-case',
                'explicit-timer-delay',
                'max-nested-calls',
                'new-for-builtins',
                'no-abusive-eslint-disable',
                'no-accessor-recursion',
                'no-anonymous-default-export',
                'no-array-fill-with-reference-type',
                'no-array-for-each',
                'no-array-method-this-argument',
                'no-array-reduce',
                'no-array-reverse',
                'no-array-sort',
                'no-await-expression-member',
                'no-await-in-promise-methods',
                'no-confusing-array-with',
                'no-console-spaces',
                'no-document-cookie',
                'no-empty-file',
                'no-hex-escape',
                'no-immediate-mutation',
                'no-instanceof-builtins',
                'no-invalid-fetch-options',
                'no-invalid-remove-event-listener',
                'no-length-as-slice-end',
                'no-lonely-if',
                'no-magic-array-flat-depth',
                'no-negated-condition',
                'no-negation-in-equality-check',
                'no-new-array',
                'no-new-buffer',
                'no-object-as-default-parameter',
                'no-process-exit',
                'no-single-promise-in-promise-methods',
                'no-static-only-class',
                'no-thenable',
                'no-this-assignment',
                'no-typeof-undefined',
                'no-unnecessary-array-flat-depth',
                'no-unnecessary-array-splice-count',
                'no-unnecessary-await',
                'no-unnecessary-slice-end',
                'no-unreadable-array-destructuring',
                'no-unreadable-iife',
                'no-useless-collection-argument',
                'no-useless-error-capture-stack-trace',
                'no-useless-fallback-in-spread',
                'no-useless-length-check',
                'no-useless-promise-resolve-reject',
                'no-useless-spread',
                'no-useless-switch-case',
                'no-useless-undefined',
                'no-zero-fractions',
                'numeric-separators-style',
                'prefer-add-event-listener',
                'prefer-array-find',
                'prefer-array-flat',
                'prefer-array-flat-map',
                'prefer-array-index-of',
                'prefer-array-some',
                'prefer-at',
                'prefer-bigint-literals',
                'prefer-blob-reading-methods',
                'prefer-class-fields',
                'prefer-classlist-toggle',
                'prefer-code-point',
                'prefer-date-now',
                'prefer-default-parameters',
                'prefer-dom-node-append',
                'prefer-dom-node-dataset',
                'prefer-dom-node-remove',
                'prefer-dom-node-text-content',
                'prefer-event-target',
                'prefer-export-from',
                'prefer-global-this',
                'prefer-import-meta-properties',
                'prefer-keyboard-event-key',
                'prefer-logical-operator-over-ternary',
                'prefer-math-min-max',
                'prefer-math-trunc',
                'prefer-modern-dom-apis',
                'prefer-modern-math-apis',
                'prefer-module',
                'prefer-native-coercion-functions',
                'prefer-negative-index',
                'prefer-node-protocol',
                'prefer-number-properties',
                'prefer-object-from-entries',
                'prefer-optional-catch-binding',
                'prefer-prototype-methods',
                'prefer-query-selector',
                'prefer-reflect-apply',
                'prefer-regexp-test',
                'prefer-response-static-json',
                'prefer-set-has',
                'prefer-set-size',
                'prefer-single-call',
                'prefer-spread',
                'prefer-string-raw',
                'prefer-string-replace-all',
                'prefer-string-slice',
                'prefer-string-trim-start-end',
                'prefer-structured-clone',
                'prefer-ternary',
                'prefer-top-level-await',
                'prefer-type-error',
                'relative-url-style',
                'require-array-join-separator',
                'require-module-attributes',
                'require-module-specifiers',
                'require-number-to-fixed-digits-argument',
                'require-post-message-target-origin',
                'switch-case-braces',
                'switch-case-break-position',
                'throw-new-error',
            ].map((rule) => `unicorn/${rule}`),
        ),

        // -- On, at the strictest value the option carries ---------------------
        'unicorn/filename-case': on([{ case: 'kebabCase' }]),
        /* The estate imports a Node builtin by name — `import { resolve } from
         * 'node:path'` — because that is what the type-aware rules read and what
         * `verbatimModuleSyntax` keeps. The rule's default asks for the default
         * import on exactly these three. */
        'unicorn/import-style': on([
            {
                styles: {
                    'node:path': { named: true },
                    'node:util': { named: true },
                    path: { named: true },
                    util: { named: true },
                },
            },
        ]),
        /* No `withDash`: the estate writes `'utf8'`, which is the rule's own
         * default preference, and `'utf-8'` is the same encoding spelled longer. */
        'unicorn/text-encoding-identifier-case': on(),

        // -- Off, each with its one reason -------------------------------------
        'unicorn/explicit-length-check': off({
            by: 'typescript/strict-boolean-expressions — it already refuses a length used as a condition',
            kind: 'covered',
        }),
        'unicorn/no-array-callback-reference': off({
            by: 'measured on this package — every report was a correct point-free callback',
            kind: 'evidence',
        }),
        'unicorn/no-instanceof-array': off({
            by: 'unicorn/no-instanceof-builtins — its upstream successor',
            kind: 'covered',
        }),
        'unicorn/no-nested-ternary': off({
            by: 'oxfmt — its fixer parenthesises the inner ternary and the formatter strips the parentheses, so every fix round ping-pongs',
            kind: 'formatter',
        }),
        'unicorn/no-null': off({
            by: 'docs/07-lint-presets.md — null is what the platform and JSON APIs return, and a codebase that refuses it grows a translation layer at every boundary',
            kind: 'convention',
        }),
        'unicorn/prefer-number-coercion': off({
            by: 'measured on this package — it rewrites `Number.parseInt("01-architecture.md", 10)`, which is 1, into `Math.trunc(Number(...))`, which is NaN; the rule assumes the string holds nothing but digits',
            kind: 'evidence',
        }),
        'unicorn/number-literal-case': off({
            by: 'oxfmt — oxc#21949: the two disagree on the case of a hex literal and rewrite each other',
            kind: 'formatter',
        }),
        'unicorn/prefer-includes': off({
            by: 'typescript/prefer-includes — the type-aware rule of the same name',
            kind: 'covered',
        }),
        'unicorn/prefer-string-starts-ends-with': off({
            by: 'typescript/prefer-string-starts-ends-with — the type-aware rule of the same name',
            kind: 'covered',
        }),
    },
});
