import { defineConfig } from 'rolldown';
import { dts } from 'rolldown-plugin-dts';

// Externalize all dependencies (node built-ins + node_modules)
const external = [/node_modules/, /^node:/, /^[a-z@]/];

// ESM build with .d.ts generation
const esmBuild = defineConfig({
    input: './src/index.ts',
    external,
    plugins: [
        dts({
            // Use TypeScript Go for fastest .d.ts generation (experimental)
            tsgo: true,
        }),
    ],
    output: {
        dir: 'dist',
        format: 'esm',
        sourcemap: true,
    },
});

// CJS build (no dts - already generated by ESM build)
const cjsBuild = defineConfig({
    input: './src/index.ts',
    external,
    output: {
        file: 'dist/index.cjs',
        format: 'cjs',
        sourcemap: true,
    },
});

export default [esmBuild, cjsBuild];
