import { defineConfig } from 'rolldown';
import { dts } from 'rolldown-plugin-dts';

// ESM build with .d.ts generation
const esmBuild = defineConfig({
    input: './src/index.ts',
    plugins: [
        dts({
            // Use TypeScript Go for fastest .d.ts generation (experimental)
            tsgo: true,
        }),
    ],
    output: {
        dir: 'dist',
        format: 'esm',
        sourcemap: true,
    },
});

// CJS build (no dts - already generated by ESM build)
const cjsBuild = defineConfig({
    input: './src/index.ts',
    output: {
        file: 'dist/index.cjs',
        format: 'cjs',
        sourcemap: true,
    },
});

export default [esmBuild, cjsBuild];
