import { existsSync } from 'node:fs';
import { defineConfig } from 'rolldown';
import { dts } from 'rolldown-plugin-dts';

// Externalize all dependencies (node built-ins + node_modules)
const external = [/node_modules/, /^node:/, /^[a-z@]/];

// Build input with optional instrumentation entry point
const input = {
    index: 'src/index.ts',
    ...(existsSync('src/instrumentation.ts') && { instrumentation: 'src/instrumentation.ts' }),
};

// ESM build with .d.ts generation
const esmBuild = defineConfig({
    input,
    external,
    plugins: [
        dts({
            // Use TypeScript Go for fastest .d.ts generation (experimental)
            tsgo: true,
        }),
    ],
    output: {
        dir: 'dist',
        format: 'esm',
        sourcemap: true,
    },
});

// CJS build (no dts - already generated by ESM build)
const cjsBuild = defineConfig({
    input,
    external,
    output: {
        dir: 'dist',
        entryFileNames: '[name].cjs',
        format: 'cjs',
        sourcemap: true,
    },
});

export default [esmBuild, cjsBuild];
