import { expect, test } from 'vitest';

import { cli } from '../cli.specification.js';

/* The first-line marker every generated file carries so a reader (or an agent) knows the file is a projection, not a source of truth. */
const GEN_HEADER = '<!-- GENERATED by `typescript docs` — DO NOT EDIT -->';

test('compiles the committed docs projection for a documented library', async () => {
    // Given - a documented library: a public API plus hand-written chapters
    const result = await cli.fixture('$FIXTURES/sample-documented/').exec('docs');

    // Then - generation succeeds and the whole stdout matches (volatile temp path tokenized)
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toMatch('docs.txt');

    // Then - the committed docs/ tree matches byte-for-byte (reference tree + chapters)
    await expect(result.directory('docs')).toMatch('docs');
});

test('stamps every generated file with the do-not-edit header', async () => {
    // Given - a freshly generated docs tree
    const result = await cli.fixture('$FIXTURES/sample-documented/').exec('docs');

    // Then - the reference index and a reference leaf self-identify
    expect(result.file('docs/reference/index.md').content).toContain(GEN_HEADER);
    expect(result.file('docs/reference/functions/greet.md').content).toContain(GEN_HEADER);
});

test('emits the full reference member set including enumerations', async () => {
    // Given - a library exporting a function, an enum, a type, and a variable
    const result = await cli.fixture('$FIXTURES/sample-documented/').exec('docs');

    // Then - typedoc's member tree carries every category, enumerations included
    const files = await result.directory('docs/reference').files();
    expect(files).toEqual([
        'enumerations/Level.md',
        'functions/add.md',
        'functions/greet.md',
        'index.md',
        'type-aliases/User.md',
        'variables/VERSION.md',
    ]);
});
